name: API CI
#on: [push]
on:
  push:
    paths:
      - "./qr-generator-vue-3/**"
      - ".github/workflows/api-ci.yml"

defaults:
  run:
    working-directory: ./qr-generator-vue-3

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'npm'
      - name: install
        shell: bash
        run: npm ci
      - name: run unit test
        shell: bash
        run: npm run test:unit



 
